#!/usr/bin/perl -w
use utf8;
use strict;
use warnings FATAL => 'uninitialized';
use lib '.';
use Yate v0.250;
use Yate::Module;
use Dyatel::ExtConfig;

$|=1;

# Operation:
# 1. [sig/xxx = callerid] <--- [dumb/xxx = dumb1]
# 2.                                              [dumb/xxx = dumb2] ---> [iax/xxx = targetid]
# 3. [sig/xxx = callerid] ----------------------------------------------> [iax/xxx = targetid]

# "caller-called" => { callerid=>id, calledid=>id, caller=>nnn, called=>nnn }
my %calls;
my %byid;

my $debug = 0;
my $count_all = 0;
my $count_connected = 0;

sub purge_call
{
	my($call, $reason) = @_;
	my $id = $call->{caller}."-".$call->{called};
	print "Purging call $id: $reason\n";
	delete $calls{$id};
	foreach my $k(qw( callerid calledid dumb1 dumb2 )) {
		delete $byid{$call->{$k}} if $call->{$k};
	}
}

# Handler for our "private" message, posted by some other script.
# Initialize "Call" structure and initiate call to originator.
sub on_call_sconnect
{
	my $msg = shift;
	my $caller = $msg->param('from');
	my $called = $msg->param('to');
	return undef unless $caller && $called;
	print "Trying to connect $caller and $called\n";
	my $id = "$caller-$called";
	my $call = $calls{$id} = {
		caller => $caller,
		called => $called,
	};
	$msg->param('autoring', 'false');

	my $msgid = $msg->generate_id;
	$byid{$msgid} = $call; # Store message id to get associate reponse with our call
	$called =~ s#\D##; # clean up caller so Ericsson will not shit off
	$msg->message('call.execute', undef, $msgid,
		caller => $called,
		callto => 'dumb/',
		target => $caller,
	);
	++$count_all;
	return('true');
}

# Called 2 times:
#  First, when we call "originator" (we get his channel id)
#  Second, when we call "destination" (we get their channel id)
sub on_our_call_execute_result
{
	my $msg = shift;
	my $call = delete $byid{$msg->header('id')} || return;
	my $targetid = $msg->param('targetid');
	my $dumbid = $msg->param('id');
	if(! $call->{callerid}) { # First case
		$msg->dumpmsg('Our call to originator (result)') if $debug;
		$call->{dumb1} = $dumbid;
		$call->{callerid} = $targetid;
	} elsif(! $call->{calledid}) { # Second case
		$msg->dumpmsg('Our call to destination (result)') if $debug;
		$call->{dumb2} = $dumbid;
		$call->{calledid} = $targetid;
	} else {
		warn "Got call.execute response but both channels ids is already set";
	}
	$byid{$targetid} = $call;
	$byid{$dumbid} = $call;
}

sub on_call_answered
{
	my $msg = shift;
	my $id = $msg->param('id');
	my $targetid = $msg->param('targetid');
	my $call = $byid{$id} || $byid{$targetid || ''} || return undef;

	if($id eq $call->{callerid} or $targetid eq $call->{dumb1}) {
		$msg->dumpmsg('Originator answered, going on') if $debug;

		my $msgid = $msg->generate_id;
		$byid{$msgid} = $call; # Store message id to get associate reponse with our call
		$msg->message('call.execute', undef, $msgid,
			caller => $call->{caller},
			callto => 'dumb/',
			target => $call->{called},
			context => 'internal',
			copyparams => 'context',
		);
	} else {
		$msg->dumpmsg('Destination answered, interconnecting channels') if $debug;
		$call->{calledid} = $id; # force answered destination channel, avoiding fork's complications
		$msg->message('chan.connect', undef, undef,
			id => $call->{callerid},
			targetid => $call->{calledid},
			billid => $msg->param('billid'),
		);
		++$count_connected;
		purge_call($call, 'connected');
	}
	return undef;
}

# Called when someone disconnects. Clean up our structures.
sub on_chan_hangup
{
	my $msg = shift;
	my $id = $msg->param('id');
	my $call = $byid{$id} || return undef;
	$msg->dumpmsg('Got hangup') if $debug;

	my $peerid = $call->{ ($id eq $call->{callerid})?'dumb2':'dumb1' };
	$msg->message('call.drop', undef, undef,
		id => $peerid,
		reason => 'Peer hangup',
	) if $peerid;

	my $reason = $msg->param('reason') || 'hangup';
	purge_call($call, $reason);
	return undef;
}

# Forward destination channel "ringing" to originator channel (inband only)
sub on_call_ringing
{
	my $msg = shift;
	my $call = $byid{$msg->param('id')} || $byid{$msg->param('targetid')} || return undef;
	my $targetid = $msg->{targetid};
	$msg->dumpmsg('Target is ringing now, so do we') if $debug;
	$msg->message('chan.masquerade', undef, undef,
		message => "chan.attach",
		id=>$call->{dumb1},
		source=>"tone/ring",
	);
	return 'true';
}

sub on_chan_replaced
{
	my $msg = shift;
	my $id = $msg->param('id');
	my $call = $byid{$id} || return undef;
	$msg->dumpmsg('Someone is replacing our channel') if $debug;
	my $newid = $msg->param('newid');
	$byid{$newid} = delete $byid{$id};
	foreach my $k(qw( callerid calledid )) {
		$call->{$k} = $newid if $id eq ($call->{$k}||'');
	}
}

# Report module status
sub make_status
{
	my($details) = @_;
	my $mystatus = '';
	$mystatus = "format=caller|callerid|called|calledid;";
	$mystatus .= "calls=$count_all,connected=$count_connected,active=".scalar(keys(%calls));
	if($details) {
		$mystatus .= ",calls=".scalar(keys(%calls)). ",byid=".scalar(keys(%byid));
		my $sep = ';';
		foreach my $k(sort keys %calls) {
			my $c = $calls{$k};
			$mystatus .= "${sep}$k=$c->{caller}|".($c->{callerid}||'-')."|$c->{called}|".($c->{calledid}||'-');
			$sep = ',';
		}
	}
	return $mystatus;
}


my $conf = Dyatel::ExtConfig::load()->{Model}{Yate}{extmodule};

my $message = new Yate(Debug=>0);
$message->connect($conf->{address}.':'.$conf->{port}, 'global', $0);
$message->install("call.sconnect",\&on_call_sconnect,200);
$message->install_incoming('call.execute', \&on_our_call_execute_result);
$message->install("call.answered",\&on_call_answered,50);
$message->install("chan.hangup",\&on_chan_hangup,50);
$message->install("call.ringing",\&on_call_ringing,50);
$message->install("chan.replaced",\&on_chan_replaced,50);
my $ym = Yate::Module->new($message);
$ym->handle_status(\&make_status);
$ym->handle_debug(sub {
	$debug = Yate::Module::_to_boolean($_[0], $debug);
	return "debug is now $debug\r\n";
});
$message->listen();




