package Dyatel::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Dyatel::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=dyatel',
        user => 'dyatel',
        password => '',
    }
);

=head1 NAME

Dyatel::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Dyatel>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Dyatel::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR

Vasily i. Redkin

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
